### ISSUE TITLE
clamav / amavis groups

### ISSUE THREAD

**Issue by andyleejordan** [mjhas/clamav#1]
So I ran into the issue that the `clamav` and `amavis` users need to belong to each others' groups ([per here](http://wiki.centos.org/HowTos/Amavisd#head-24112092d2c8980d9a588faddf32b4ede7517cc9), or you get an error like in [this thread](http://www.linuxquestions.org/questions/linux-server-73/permission-denied-between-clamav-daemon-and-amavisd-new-on-ubuntu-9-04-a-722668/).

Neither module handles this, nor does it belong in either module. Perhaps it'd be a well-fit for your mailserver module (heck it may already do it). Regardless, let's get it documented.

**Comment by mjhas** [comment]
you're right, that was totally forgotten by me. patch pending ;)

**Comment by andyleejordan** [comment]
It's all good. I've had a fun time getting this all setup. I had to disable ClamAV and AMaViS to get Postfix working right (plus the former is a memory hog). I'm working on getting Spamassassin alone going.
